export interface PokemonData {
    id: number;
    name: string;
    types: string[];
    height: number; // in meters
    weight: number; // in kg
    habitat: string;
    evolutionStage: number;
}

export const POKEMON_DATA: PokemonData[] = [
  { id: 1, name: 'Bulbasaur', types: [ 'grass', 'poison' ], height: 0.7, weight: 6.9, habitat: 'grassland', evolutionStage: 1 },
  { id: 2, name: 'Ivysaur', types: [ 'grass', 'poison' ], height: 1, weight: 13, habitat: 'grassland', evolutionStage: 2 },
  { id: 3, name: 'Venusaur', types: [ 'grass', 'poison' ], height: 2, weight: 100, habitat: 'grassland', evolutionStage: 3 },
  { id: 4, name: 'Charmander', types: [ 'fire' ], height: 0.6, weight: 8.5, habitat: 'mountain', evolutionStage: 1 },
  { id: 5, name: 'Charmeleon', types: [ 'fire' ], height: 1.1, weight: 19, habitat: 'mountain', evolutionStage: 2 },
  { id: 6, name: 'Charizard', types: [ 'fire', 'flying' ], height: 1.7, weight: 90.5, habitat: 'mountain', evolutionStage: 3 },
  { id: 7, name: 'Squirtle', types: [ 'water' ], height: 0.5, weight: 9, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 8, name: 'Wartortle', types: [ 'water' ], height: 1, weight: 22.5, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 9, name: 'Blastoise', types: [ 'water' ], height: 1.6, weight: 85.5, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 10, name: 'Caterpie', types: [ 'bug' ], height: 0.3, weight: 2.9, habitat: 'forest', evolutionStage: 1 },
  { id: 11, name: 'Metapod', types: [ 'bug' ], height: 0.7, weight: 9.9, habitat: 'forest', evolutionStage: 2 },
  { id: 12, name: 'Butterfree', types: [ 'bug', 'flying' ], height: 1.1, weight: 32, habitat: 'forest', evolutionStage: 3 },
  { id: 13, name: 'Weedle', types: [ 'bug', 'poison' ], height: 0.3, weight: 3.2, habitat: 'forest', evolutionStage: 1 },
  { id: 14, name: 'Kakuna', types: [ 'bug', 'poison' ], height: 0.6, weight: 10, habitat: 'forest', evolutionStage: 2 },
  { id: 15, name: 'Beedrill', types: [ 'bug', 'poison' ], height: 1, weight: 29.5, habitat: 'forest', evolutionStage: 3 },
  { id: 16, name: 'Pidgey', types: [ 'normal', 'flying' ], height: 0.3, weight: 1.8, habitat: 'forest', evolutionStage: 1 },
  { id: 17, name: 'Pidgeotto', types: [ 'normal', 'flying' ], height: 1.1, weight: 30, habitat: 'forest', evolutionStage: 2 },
  { id: 18, name: 'Pidgeot', types: [ 'normal', 'flying' ], height: 1.5, weight: 39.5, habitat: 'forest', evolutionStage: 3 },
  { id: 19, name: 'Rattata', types: [ 'normal' ], height: 0.3, weight: 3.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 20, name: 'Raticate', types: [ 'normal' ], height: 0.7, weight: 18.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 21, name: 'Spearow', types: [ 'normal', 'flying' ], height: 0.3, weight: 2, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 22, name: 'Fearow', types: [ 'normal', 'flying' ], height: 1.2, weight: 38, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 23, name: 'Ekans', types: [ 'poison' ], height: 2, weight: 6.9, habitat: 'grassland', evolutionStage: 1 },
  { id: 24, name: 'Arbok', types: [ 'poison' ], height: 3.5, weight: 65, habitat: 'grassland', evolutionStage: 2 },
  { id: 25, name: 'Pikachu', types: [ 'electric' ], height: 0.4, weight: 6, habitat: 'forest', evolutionStage: 2 },
  { id: 26, name: 'Raichu', types: [ 'electric' ], height: 0.8, weight: 30, habitat: 'forest', evolutionStage: 3 },
  { id: 27, name: 'Sandshrew', types: [ 'ground' ], height: 0.6, weight: 12, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 28, name: 'Sandslash', types: [ 'ground' ], height: 1, weight: 29.5, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 29, name: 'Nidoran♀', types: [ 'poison' ], height: 0.4, weight: 7, habitat: 'grassland', evolutionStage: 1 },
  { id: 30, name: 'Nidorina', types: [ 'poison' ], height: 0.8, weight: 20, habitat: 'grassland', evolutionStage: 2 },
  { id: 31, name: 'Nidoqueen', types: [ 'poison', 'ground' ], height: 1.3, weight: 60, habitat: 'grassland', evolutionStage: 3 },
  { id: 32, name: 'Nidoran♂', types: [ 'poison' ], height: 0.5, weight: 9, habitat: 'grassland', evolutionStage: 1 },
  { id: 33, name: 'Nidorino', types: [ 'poison' ], height: 0.9, weight: 19.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 34, name: 'Nidoking', types: [ 'poison', 'ground' ], height: 1.4, weight: 62, habitat: 'grassland', evolutionStage: 3 },
  { id: 35, name: 'Clefairy', types: [ 'fairy' ], height: 0.6, weight: 7.5, habitat: 'mountain', evolutionStage: 2 },
  { id: 36, name: 'Clefable', types: [ 'fairy' ], height: 1.3, weight: 40, habitat: 'mountain', evolutionStage: 3 },
  { id: 37, name: 'Vulpix', types: [ 'fire' ], height: 0.6, weight: 9.9, habitat: 'grassland', evolutionStage: 1 },
  { id: 38, name: 'Ninetales', types: [ 'fire' ], height: 1.1, weight: 19.9, habitat: 'grassland', evolutionStage: 2 },
  { id: 39, name: 'Jigglypuff', types: [ 'normal', 'fairy' ], height: 0.5, weight: 5.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 40, name: 'Wigglytuff', types: [ 'normal', 'fairy' ], height: 1, weight: 12, habitat: 'grassland', evolutionStage: 3 },
  { id: 41, name: 'Zubat', types: [ 'poison', 'flying' ], height: 0.8, weight: 7.5, habitat: 'cave', evolutionStage: 1 },
  { id: 42, name: 'Golbat', types: [ 'poison', 'flying' ], height: 1.6, weight: 55, habitat: 'cave', evolutionStage: 2 },
  { id: 43, name: 'Oddish', types: [ 'grass', 'poison' ], height: 0.5, weight: 5.4, habitat: 'grassland', evolutionStage: 1 },
  { id: 44, name: 'Gloom', types: [ 'grass', 'poison' ], height: 0.8, weight: 8.6, habitat: 'grassland', evolutionStage: 2 },
  { id: 45, name: 'Vileplume', types: [ 'grass', 'poison' ], height: 1.2, weight: 18.6, habitat: 'grassland', evolutionStage: 3 },
  { id: 46, name: 'Paras', types: [ 'bug', 'grass' ], height: 0.3, weight: 5.4, habitat: 'forest', evolutionStage: 1 },
  { id: 47, name: 'Parasect', types: [ 'bug', 'grass' ], height: 1, weight: 29.5, habitat: 'forest', evolutionStage: 2 },
  { id: 48, name: 'Venonat', types: [ 'bug', 'poison' ], height: 1, weight: 30, habitat: 'forest', evolutionStage: 1 },
  { id: 49, name: 'Venomoth', types: [ 'bug', 'poison' ], height: 1.5, weight: 12.5, habitat: 'forest', evolutionStage: 2 },
  { id: 50, name: 'Diglett', types: [ 'ground' ], height: 0.2, weight: 0.8, habitat: 'cave', evolutionStage: 1 },
  { id: 51, name: 'Dugtrio', types: [ 'ground' ], height: 0.7, weight: 33.3, habitat: 'cave', evolutionStage: 2 },
  { id: 52, name: 'Meowth', types: [ 'normal' ], height: 0.4, weight: 4.2, habitat: 'urban', evolutionStage: 1 },
  { id: 53, name: 'Persian', types: [ 'normal' ], height: 1, weight: 32, habitat: 'urban', evolutionStage: 2 },
  { id: 54, name: 'Psyduck', types: [ 'water' ], height: 0.8, weight: 19.6, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 55, name: 'Golduck', types: [ 'water' ], height: 1.7, weight: 76.6, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 56, name: 'Mankey', types: [ 'fighting' ], height: 0.5, weight: 28, habitat: 'mountain', evolutionStage: 1 },
  { id: 57, name: 'Primeape', types: [ 'fighting' ], height: 1, weight: 32, habitat: 'mountain', evolutionStage: 2 },
  { id: 58, name: 'Growlithe', types: [ 'fire' ], height: 0.7, weight: 19, habitat: 'grassland', evolutionStage: 1 },
  { id: 59, name: 'Arcanine', types: [ 'fire' ], height: 1.9, weight: 155, habitat: 'grassland', evolutionStage: 2 },
  { id: 60, name: 'Poliwag', types: [ 'water' ], height: 0.6, weight: 12.4, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 61, name: 'Poliwhirl', types: [ 'water' ], height: 1, weight: 20, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 62, name: 'Poliwrath', types: [ 'water', 'fighting' ], height: 1.3, weight: 54, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 63, name: 'Abra', types: [ 'psychic' ], height: 0.9, weight: 19.5, habitat: 'urban', evolutionStage: 1 },
  { id: 64, name: 'Kadabra', types: [ 'psychic' ], height: 1.3, weight: 56.5, habitat: 'urban', evolutionStage: 2 },
  { id: 65, name: 'Alakazam', types: [ 'psychic' ], height: 1.5, weight: 48, habitat: 'urban', evolutionStage: 3 },
  { id: 66, name: 'Machop', types: [ 'fighting' ], height: 0.8, weight: 19.5, habitat: 'mountain', evolutionStage: 1 },
  { id: 67, name: 'Machoke', types: [ 'fighting' ], height: 1.5, weight: 70.5, habitat: 'mountain', evolutionStage: 2 },
  { id: 68, name: 'Machamp', types: [ 'fighting' ], height: 1.6, weight: 130, habitat: 'mountain', evolutionStage: 3 },
  { id: 69, name: 'Bellsprout', types: [ 'grass', 'poison' ], height: 0.7, weight: 4, habitat: 'forest', evolutionStage: 1 },
  { id: 70, name: 'Weepinbell', types: [ 'grass', 'poison' ], height: 1, weight: 6.4, habitat: 'forest', evolutionStage: 2 },
  { id: 71, name: 'Victreebel', types: [ 'grass', 'poison' ], height: 1.7, weight: 15.5, habitat: 'forest', evolutionStage: 3 },
  { id: 72, name: 'Tentacool', types: [ 'water', 'poison' ], height: 0.9, weight: 45.5, habitat: 'sea', evolutionStage: 1 },
  { id: 73, name: 'Tentacruel', types: [ 'water', 'poison' ], height: 1.6, weight: 55, habitat: 'sea', evolutionStage: 2 },
  { id: 74, name: 'Geodude', types: [ 'rock', 'ground' ], height: 0.4, weight: 20, habitat: 'mountain', evolutionStage: 1 },
  { id: 75, name: 'Graveler', types: [ 'rock', 'ground' ], height: 1, weight: 105, habitat: 'mountain', evolutionStage: 2 },
  { id: 76, name: 'Golem', types: [ 'rock', 'ground' ], height: 1.4, weight: 300, habitat: 'mountain', evolutionStage: 3 },
  { id: 77, name: 'Ponyta', types: [ 'fire' ], height: 1, weight: 30, habitat: 'grassland', evolutionStage: 1 },
  { id: 78, name: 'Rapidash', types: [ 'fire' ], height: 1.7, weight: 95, habitat: 'grassland', evolutionStage: 2 },
  { id: 79, name: 'Slowpoke', types: [ 'water', 'psychic' ], height: 1.2, weight: 36, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 80, name: 'Slowbro', types: [ 'water', 'psychic' ], height: 1.6, weight: 78.5, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 81, name: 'Magnemite', types: [ 'electric', 'steel' ], height: 0.3, weight: 6, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 82, name: 'Magneton', types: [ 'electric', 'steel' ], height: 1, weight: 60, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 83, name: 'Farfetch\'d', types: [ 'normal', 'flying' ], height: 0.8, weight: 15, habitat: 'grassland', evolutionStage: 1 },
  { id: 84, name: 'Doduo', types: [ 'normal', 'flying' ], height: 1.4, weight: 39.2, habitat: 'grassland', evolutionStage: 1 },
  { id: 85, name: 'Dodrio', types: [ 'normal', 'flying' ], height: 1.8, weight: 85.2, habitat: 'grassland', evolutionStage: 2 },
  { id: 86, name: 'Seel', types: [ 'water' ], height: 1.1, weight: 90, habitat: 'sea', evolutionStage: 1 },
  { id: 87, name: 'Dewgong', types: [ 'water', 'ice' ], height: 1.7, weight: 120, habitat: 'sea', evolutionStage: 2 },
  { id: 88, name: 'Grimer', types: [ 'poison' ], height: 0.9, weight: 30, habitat: 'urban', evolutionStage: 1 },
  { id: 89, name: 'Muk', types: [ 'poison' ], height: 1.2, weight: 30, habitat: 'urban', evolutionStage: 2 },
  { id: 90, name: 'Shellder', types: [ 'water' ], height: 0.3, weight: 4, habitat: 'sea', evolutionStage: 1 },
  { id: 91, name: 'Cloyster', types: [ 'water', 'ice' ], height: 1.5, weight: 132.5, habitat: 'sea', evolutionStage: 2 },
  { id: 92, name: 'Gastly', types: [ 'ghost', 'poison' ], height: 1.3, weight: 0.1, habitat: 'cave', evolutionStage: 1 },
  { id: 93, name: 'Haunter', types: [ 'ghost', 'poison' ], height: 1.6, weight: 0.1, habitat: 'cave', evolutionStage: 2 },
  { id: 94, name: 'Gengar', types: [ 'ghost', 'poison' ], height: 1.5, weight: 40.5, habitat: 'cave', evolutionStage: 3 },
  { id: 95, name: 'Onix', types: [ 'rock', 'ground' ], height: 8.8, weight: 210, habitat: 'cave', evolutionStage: 1 },
  { id: 96, name: 'Drowzee', types: [ 'psychic' ], height: 1, weight: 32.4, habitat: 'grassland', evolutionStage: 1 },
  { id: 97, name: 'Hypno', types: [ 'psychic' ], height: 1.6, weight: 75.6, habitat: 'grassland', evolutionStage: 2 },
  { id: 98, name: 'Krabby', types: [ 'water' ], height: 0.4, weight: 6.5, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 99, name: 'Kingler', types: [ 'water' ], height: 1.3, weight: 60, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 100, name: 'Voltorb', types: [ 'electric' ], height: 0.5, weight: 10.4, habitat: 'urban', evolutionStage: 1 },
  { id: 101, name: 'Electrode', types: [ 'electric' ], height: 1.2, weight: 66.6, habitat: 'urban', evolutionStage: 2 },
  { id: 102, name: 'Exeggcute', types: [ 'grass', 'psychic' ], height: 0.4, weight: 2.5, habitat: 'forest', evolutionStage: 1 },
  { id: 103, name: 'Exeggutor', types: [ 'grass', 'psychic' ], height: 2, weight: 120, habitat: 'forest', evolutionStage: 2 },
  { id: 104, name: 'Cubone', types: [ 'ground' ], height: 0.4, weight: 6.5, habitat: 'mountain', evolutionStage: 1 },
  { id: 105, name: 'Marowak', types: [ 'ground' ], height: 1, weight: 45, habitat: 'mountain', evolutionStage: 2 },
  { id: 106, name: 'Hitmonlee', types: [ 'fighting' ], height: 1.5, weight: 49.8, habitat: 'urban', evolutionStage: 2 },
  { id: 107, name: 'Hitmonchan', types: [ 'fighting' ], height: 1.4, weight: 50.2, habitat: 'urban', evolutionStage: 2 },
  { id: 108, name: 'Lickitung', types: [ 'normal' ], height: 1.2, weight: 65.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 109, name: 'Koffing', types: [ 'poison' ], height: 0.6, weight: 1, habitat: 'urban', evolutionStage: 1 },
  { id: 110, name: 'Weezing', types: [ 'poison' ], height: 1.2, weight: 9.5, habitat: 'urban', evolutionStage: 2 },
  { id: 111, name: 'Rhyhorn', types: [ 'rock', 'ground' ], height: 1, weight: 115, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 112, name: 'Rhydon', types: [ 'rock', 'ground' ], height: 1.9, weight: 120, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 113, name: 'Chansey', types: [ 'normal' ], height: 1.1, weight: 34.6, habitat: 'urban', evolutionStage: 2 },
  { id: 114, name: 'Tangela', types: [ 'grass' ], height: 1, weight: 35, habitat: 'grassland', evolutionStage: 1 },
  { id: 115, name: 'Kangaskhan', types: [ 'normal' ], height: 2.2, weight: 80, habitat: 'grassland', evolutionStage: 1 },
  { id: 116, name: 'Horsea', types: [ 'water' ], height: 0.4, weight: 8, habitat: 'sea', evolutionStage: 1 },
  { id: 117, name: 'Seadra', types: [ 'water' ], height: 1.2, weight: 25, habitat: 'sea', evolutionStage: 2 },
  { id: 118, name: 'Goldeen', types: [ 'water' ], height: 0.6, weight: 15, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 119, name: 'Seaking', types: [ 'water' ], height: 1.3, weight: 39, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 120, name: 'Staryu', types: [ 'water' ], height: 0.8, weight: 34.5, habitat: 'sea', evolutionStage: 1 },
  { id: 121, name: 'Starmie', types: [ 'water', 'psychic' ], height: 1.1, weight: 80, habitat: 'sea', evolutionStage: 2 },
  { id: 122, name: 'Mr. Mime', types: [ 'psychic', 'fairy' ], height: 1.3, weight: 54.5, habitat: 'urban', evolutionStage: 2 },
  { id: 123, name: 'Scyther', types: [ 'bug', 'flying' ], height: 1.5, weight: 56, habitat: 'grassland', evolutionStage: 1 },
  { id: 124, name: 'Jynx', types: [ 'ice', 'psychic' ], height: 1.4, weight: 40.6, habitat: 'urban', evolutionStage: 2 },
  { id: 125, name: 'Electabuzz', types: [ 'electric' ], height: 1.1, weight: 30, habitat: 'grassland', evolutionStage: 2 },
  { id: 126, name: 'Magmar', types: [ 'fire' ], height: 1.3, weight: 44.5, habitat: 'mountain', evolutionStage: 2 },
  { id: 127, name: 'Pinsir', types: [ 'bug' ], height: 1.5, weight: 55, habitat: 'forest', evolutionStage: 1 },
  { id: 128, name: 'Tauros', types: [ 'normal' ], height: 1.4, weight: 88.4, habitat: 'grassland', evolutionStage: 1 },
  { id: 129, name: 'Magikarp', types: [ 'water' ], height: 0.9, weight: 10, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 130, name: 'Gyarados', types: [ 'water', 'flying' ], height: 6.5, weight: 235, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 131, name: 'Lapras', types: [ 'water', 'ice' ], height: 2.5, weight: 220, habitat: 'sea', evolutionStage: 1 },
  { id: 132, name: 'Ditto', types: [ 'normal' ], height: 0.3, weight: 4, habitat: 'urban', evolutionStage: 1 },
  { id: 133, name: 'Eevee', types: [ 'normal' ], height: 0.3, weight: 6.5, habitat: 'urban', evolutionStage: 1 },
  { id: 134, name: 'Vaporeon', types: [ 'water' ], height: 1, weight: 29, habitat: 'urban', evolutionStage: 2 },
  { id: 135, name: 'Jolteon', types: [ 'electric' ], height: 0.8, weight: 24.5, habitat: 'urban', evolutionStage: 2 },
  { id: 136, name: 'Flareon', types: [ 'fire' ], height: 0.9, weight: 25, habitat: 'urban', evolutionStage: 2 },
  { id: 137, name: 'Porygon', types: [ 'normal' ], height: 0.8, weight: 36.5, habitat: 'urban', evolutionStage: 1 },
  { id: 138, name: 'Omanyte', types: [ 'rock', 'water' ], height: 0.4, weight: 7.5, habitat: 'sea', evolutionStage: 1 },
  { id: 139, name: 'Omastar', types: [ 'rock', 'water' ], height: 1, weight: 35, habitat: 'sea', evolutionStage: 2 },
  { id: 140, name: 'Kabuto', types: [ 'rock', 'water' ], height: 0.5, weight: 11.5, habitat: 'sea', evolutionStage: 1 },
  { id: 141, name: 'Kabutops', types: [ 'rock', 'water' ], height: 1.3, weight: 40.5, habitat: 'sea', evolutionStage: 2 },
  { id: 142, name: 'Aerodactyl', types: [ 'rock', 'flying' ], height: 1.8, weight: 59, habitat: 'mountain', evolutionStage: 1 },
  { id: 143, name: 'Snorlax', types: [ 'normal' ], height: 2.1, weight: 460, habitat: 'mountain', evolutionStage: 1 },
  { id: 144, name: 'Articuno', types: [ 'ice', 'flying' ], height: 1.7, weight: 55.4, habitat: 'rare', evolutionStage: 1 },
  { id: 145, name: 'Zapdos', types: [ 'electric', 'flying' ], height: 1.6, weight: 52.6, habitat: 'rare', evolutionStage: 1 },
  { id: 146, name: 'Moltres', types: [ 'fire', 'flying' ], height: 2, weight: 60, habitat: 'rare', evolutionStage: 1 },
  { id: 147, name: 'Dratini', types: [ 'dragon' ], height: 1.8, weight: 3.3, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 148, name: 'Dragonair', types: [ 'dragon' ], height: 4, weight: 16.5, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 149, name: 'Dragonite', types: [ 'dragon', 'flying' ], height: 2.2, weight: 210, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 150, name: 'Mewtwo', types: [ 'psychic' ], height: 2, weight: 122, habitat: 'rare', evolutionStage: 1 },
  { id: 151, name: 'Mew', types: [ 'psychic' ], height: 0.4, weight: 4, habitat: 'rare', evolutionStage: 1 },
  { id: 152, name: 'Chikorita', types: [ 'grass' ], height: 0.9, weight: 6.4, habitat: 'grassland', evolutionStage: 1 },
  { id: 153, name: 'Bayleef', types: [ 'grass' ], height: 1.2, weight: 15.8, habitat: 'grassland', evolutionStage: 2 },
  { id: 154, name: 'Meganium', types: [ 'grass' ], height: 1.8, weight: 100.5, habitat: 'grassland', evolutionStage: 3 },
  { id: 155, name: 'Cyndaquil', types: [ 'fire' ], height: 0.5, weight: 7.9, habitat: 'grassland', evolutionStage: 1 },
  { id: 156, name: 'Quilava', types: [ 'fire' ], height: 0.9, weight: 19, habitat: 'grassland', evolutionStage: 2 },
  { id: 157, name: 'Typhlosion', types: [ 'fire' ], height: 1.7, weight: 79.5, habitat: 'grassland', evolutionStage: 3 },
  { id: 158, name: 'Totodile', types: [ 'water' ], height: 0.6, weight: 9.5, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 159, name: 'Croconaw', types: [ 'water' ], height: 1.1, weight: 25, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 160, name: 'Feraligatr', types: [ 'water' ], height: 2.3, weight: 88.8, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 161, name: 'Sentret', types: [ 'normal' ], height: 0.8, weight: 6, habitat: 'grassland', evolutionStage: 1 },
  { id: 162, name: 'Furret', types: [ 'normal' ], height: 1.8, weight: 32.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 163, name: 'Hoothoot', types: [ 'normal', 'flying' ], height: 0.7, weight: 21.2, habitat: 'forest', evolutionStage: 1 },
  { id: 164, name: 'Noctowl', types: [ 'normal', 'flying' ], height: 1.6, weight: 40.8, habitat: 'forest', evolutionStage: 2 },
  { id: 165, name: 'Ledyba', types: [ 'bug', 'flying' ], height: 1, weight: 10.8, habitat: 'forest', evolutionStage: 1 },
  { id: 166, name: 'Ledian', types: [ 'bug', 'flying' ], height: 1.4, weight: 35.6, habitat: 'forest', evolutionStage: 2 },
  { id: 167, name: 'Spinarak', types: [ 'bug', 'poison' ], height: 0.5, weight: 8.5, habitat: 'forest', evolutionStage: 1 },
  { id: 168, name: 'Ariados', types: [ 'bug', 'poison' ], height: 1.1, weight: 33.5, habitat: 'forest', evolutionStage: 2 },
  { id: 169, name: 'Crobat', types: [ 'poison', 'flying' ], height: 1.8, weight: 75, habitat: 'cave', evolutionStage: 3 },
  { id: 170, name: 'Chinchou', types: [ 'water', 'electric' ], height: 0.5, weight: 12, habitat: 'sea', evolutionStage: 1 },
  { id: 171, name: 'Lanturn', types: [ 'water', 'electric' ], height: 1.2, weight: 22.5, habitat: 'sea', evolutionStage: 2 },
  { id: 172, name: 'Pichu', types: [ 'electric' ], height: 0.3, weight: 2, habitat: 'forest', evolutionStage: 1 },
  { id: 173, name: 'Cleffa', types: [ 'fairy' ], height: 0.3, weight: 3, habitat: 'mountain', evolutionStage: 1 },
  { id: 174, name: 'Igglybuff', types: [ 'normal', 'fairy' ], height: 0.3, weight: 1, habitat: 'grassland', evolutionStage: 1 },
  { id: 175, name: 'Togepi', types: [ 'fairy' ], height: 0.3, weight: 1.5, habitat: 'forest', evolutionStage: 1 },
  { id: 176, name: 'Togetic', types: [ 'fairy', 'flying' ], height: 0.6, weight: 3.2, habitat: 'forest', evolutionStage: 2 },
  { id: 177, name: 'Natu', types: [ 'psychic', 'flying' ], height: 0.2, weight: 2, habitat: 'forest', evolutionStage: 1 },
  { id: 178, name: 'Xatu', types: [ 'psychic', 'flying' ], height: 1.5, weight: 15, habitat: 'forest', evolutionStage: 2 },
  { id: 179, name: 'Mareep', types: [ 'electric' ], height: 0.6, weight: 7.8, habitat: 'grassland', evolutionStage: 1 },
  { id: 180, name: 'Flaaffy', types: [ 'electric' ], height: 0.8, weight: 13.3, habitat: 'grassland', evolutionStage: 2 },
  { id: 181, name: 'Ampharos', types: [ 'electric' ], height: 1.4, weight: 61.5, habitat: 'grassland', evolutionStage: 3 },
  { id: 182, name: 'Bellossom', types: [ 'grass' ], height: 0.4, weight: 5.8, habitat: 'grassland', evolutionStage: 3 },
  { id: 183, name: 'Marill', types: [ 'water', 'fairy' ], height: 0.4, weight: 8.5, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 184, name: 'Azumarill', types: [ 'water', 'fairy' ], height: 0.8, weight: 28.5, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 185, name: 'Sudowoodo', types: [ 'rock' ], height: 1.2, weight: 38, habitat: 'forest', evolutionStage: 2 },
  { id: 186, name: 'Politoed', types: [ 'water' ], height: 1.1, weight: 33.9, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 187, name: 'Hoppip', types: [ 'grass', 'flying' ], height: 0.4, weight: 0.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 188, name: 'Skiploom', types: [ 'grass', 'flying' ], height: 0.6, weight: 1, habitat: 'grassland', evolutionStage: 2 },
  { id: 189, name: 'Jumpluff', types: [ 'grass', 'flying' ], height: 0.8, weight: 3, habitat: 'grassland', evolutionStage: 3 },
  { id: 190, name: 'Aipom', types: [ 'normal' ], height: 0.8, weight: 11.5, habitat: 'forest', evolutionStage: 1 },
  { id: 191, name: 'Sunkern', types: [ 'grass' ], height: 0.3, weight: 1.8, habitat: 'grassland', evolutionStage: 1 },
  { id: 192, name: 'Sunflora', types: [ 'grass' ], height: 0.8, weight: 8.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 193, name: 'Yanma', types: [ 'bug', 'flying' ], height: 1.2, weight: 38, habitat: 'forest', evolutionStage: 1 },
  { id: 194, name: 'Wooper', types: [ 'water', 'ground' ], height: 0.4, weight: 8.5, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 195, name: 'Quagsire', types: [ 'water', 'ground' ], height: 1.4, weight: 75, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 196, name: 'Espeon', types: [ 'psychic' ], height: 0.9, weight: 26.5, habitat: 'urban', evolutionStage: 2 },
  { id: 197, name: 'Umbreon', types: [ 'dark' ], height: 1, weight: 27, habitat: 'urban', evolutionStage: 2 },
  { id: 198, name: 'Murkrow', types: [ 'dark', 'flying' ], height: 0.5, weight: 2.1, habitat: 'forest', evolutionStage: 1 },
  { id: 199, name: 'Slowking', types: [ 'water', 'psychic' ], height: 2, weight: 79.5, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 200, name: 'Misdreavus', types: [ 'ghost' ], height: 0.7, weight: 1, habitat: 'cave', evolutionStage: 1 },
  { id: 201, name: 'Unown', types: [ 'psychic' ], height: 0.5, weight: 5, habitat: 'rare', evolutionStage: 1 },
  { id: 202, name: 'Wobbuffet', types: [ 'psychic' ], height: 1.3, weight: 28.5, habitat: 'cave', evolutionStage: 2 },
  { id: 203, name: 'Girafarig', types: [ 'normal', 'psychic' ], height: 1.5, weight: 41.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 204, name: 'Pineco', types: [ 'bug' ], height: 0.6, weight: 7.2, habitat: 'forest', evolutionStage: 1 },
  { id: 205, name: 'Forretress', types: [ 'bug', 'steel' ], height: 1.2, weight: 125.8, habitat: 'forest', evolutionStage: 2 },
  { id: 206, name: 'Dunsparce', types: [ 'normal' ], height: 1.5, weight: 14, habitat: 'cave', evolutionStage: 1 },
  { id: 207, name: 'Gligar', types: [ 'ground', 'flying' ], height: 1.1, weight: 64.8, habitat: 'mountain', evolutionStage: 1 },
  { id: 208, name: 'Steelix', types: [ 'steel', 'ground' ], height: 9.2, weight: 400, habitat: 'cave', evolutionStage: 2 },
  { id: 209, name: 'Snubbull', types: [ 'fairy' ], height: 0.6, weight: 7.8, habitat: 'urban', evolutionStage: 1 },
  { id: 210, name: 'Granbull', types: [ 'fairy' ], height: 1.4, weight: 48.7, habitat: 'urban', evolutionStage: 2 },
  { id: 211, name: 'Qwilfish', types: [ 'water', 'poison' ], height: 0.5, weight: 3.9, habitat: 'sea', evolutionStage: 1 },
  { id: 212, name: 'Scizor', types: [ 'bug', 'steel' ], height: 1.8, weight: 118, habitat: 'grassland', evolutionStage: 2 },
  { id: 213, name: 'Shuckle', types: [ 'bug', 'rock' ], height: 0.6, weight: 20.5, habitat: 'mountain', evolutionStage: 1 },
  { id: 214, name: 'Heracross', types: [ 'bug', 'fighting' ], height: 1.5, weight: 54, habitat: 'forest', evolutionStage: 1 },
  { id: 215, name: 'Sneasel', types: [ 'dark', 'ice' ], height: 0.9, weight: 28, habitat: 'forest', evolutionStage: 1 },
  { id: 216, name: 'Teddiursa', types: [ 'normal' ], height: 0.6, weight: 8.8, habitat: 'mountain', evolutionStage: 1 },
  { id: 217, name: 'Ursaring', types: [ 'normal' ], height: 1.8, weight: 125.8, habitat: 'mountain', evolutionStage: 2 },
  { id: 218, name: 'Slugma', types: [ 'fire' ], height: 0.7, weight: 35, habitat: 'mountain', evolutionStage: 1 },
  { id: 219, name: 'Magcargo', types: [ 'fire', 'rock' ], height: 0.8, weight: 55, habitat: 'mountain', evolutionStage: 2 },
  { id: 220, name: 'Swinub', types: [ 'ice', 'ground' ], height: 0.4, weight: 6.5, habitat: 'cave', evolutionStage: 1 },
  { id: 221, name: 'Piloswine', types: [ 'ice', 'ground' ], height: 1.1, weight: 55.8, habitat: 'cave', evolutionStage: 2 },
  { id: 222, name: 'Corsola', types: [ 'water', 'rock' ], height: 0.6, weight: 5, habitat: 'sea', evolutionStage: 1 },
  { id: 223, name: 'Remoraid', types: [ 'water' ], height: 0.6, weight: 12, habitat: 'sea', evolutionStage: 1 },
  { id: 224, name: 'Octillery', types: [ 'water' ], height: 0.9, weight: 28.5, habitat: 'sea', evolutionStage: 2 },
  { id: 225, name: 'Delibird', types: [ 'ice', 'flying' ], height: 0.9, weight: 16, habitat: 'mountain', evolutionStage: 1 },
  { id: 226, name: 'Mantine', types: [ 'water', 'flying' ], height: 2.1, weight: 220, habitat: 'sea', evolutionStage: 2 },
  { id: 227, name: 'Skarmory', types: [ 'steel', 'flying' ], height: 1.7, weight: 50.5, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 228, name: 'Houndour', types: [ 'dark', 'fire' ], height: 0.6, weight: 10.8, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 229, name: 'Houndoom', types: [ 'dark', 'fire' ], height: 1.4, weight: 35, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 230, name: 'Kingdra', types: [ 'water', 'dragon' ], height: 1.8, weight: 152, habitat: 'sea', evolutionStage: 3 },
  { id: 231, name: 'Phanpy', types: [ 'ground' ], height: 0.5, weight: 33.5, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 232, name: 'Donphan', types: [ 'ground' ], height: 1.1, weight: 120, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 233, name: 'Porygon2', types: [ 'normal' ], height: 0.6, weight: 32.5, habitat: 'urban', evolutionStage: 2 },
  { id: 234, name: 'Stantler', types: [ 'normal' ], height: 1.4, weight: 71.2, habitat: 'forest', evolutionStage: 1 },
  { id: 235, name: 'Smeargle', types: [ 'normal' ], height: 1.2, weight: 58, habitat: 'urban', evolutionStage: 1 },
  { id: 236, name: 'Tyrogue', types: [ 'fighting' ], height: 0.7, weight: 21, habitat: 'urban', evolutionStage: 1 },
  { id: 237, name: 'Hitmontop', types: [ 'fighting' ], height: 1.4, weight: 48, habitat: 'urban', evolutionStage: 2 },
  { id: 238, name: 'Smoochum', types: [ 'ice', 'psychic' ], height: 0.4, weight: 6, habitat: 'urban', evolutionStage: 1 },
  { id: 239, name: 'Elekid', types: [ 'electric' ], height: 0.6, weight: 23.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 240, name: 'Magby', types: [ 'fire' ], height: 0.7, weight: 21.4, habitat: 'mountain', evolutionStage: 1 },
  { id: 241, name: 'Miltank', types: [ 'normal' ], height: 1.2, weight: 75.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 242, name: 'Blissey', types: [ 'normal' ], height: 1.5, weight: 46.8, habitat: 'urban', evolutionStage: 3 },
  { id: 243, name: 'Raikou', types: [ 'electric' ], height: 1.9, weight: 178, habitat: 'rare', evolutionStage: 1 },
  { id: 244, name: 'Entei', types: [ 'fire' ], height: 2.1, weight: 198, habitat: 'rare', evolutionStage: 1 },
  { id: 245, name: 'Suicune', types: [ 'water' ], height: 2, weight: 187, habitat: 'rare', evolutionStage: 1 },
  { id: 246, name: 'Larvitar', types: [ 'rock', 'ground' ], height: 0.6, weight: 72, habitat: 'mountain', evolutionStage: 1 },
  { id: 247, name: 'Pupitar', types: [ 'rock', 'ground' ], height: 1.2, weight: 152, habitat: 'mountain', evolutionStage: 2 },
  { id: 248, name: 'Tyranitar', types: [ 'rock', 'dark' ], height: 2, weight: 202, habitat: 'mountain', evolutionStage: 3 },
  { id: 249, name: 'Lugia', types: [ 'psychic', 'flying' ], height: 5.2, weight: 216, habitat: 'rare', evolutionStage: 1 },
  { id: 250, name: 'Ho-Oh', types: [ 'fire', 'flying' ], height: 3.8, weight: 199, habitat: 'rare', evolutionStage: 1 },
  { id: 251, name: 'Celebi', types: [ 'psychic', 'grass' ], height: 0.6, weight: 5, habitat: 'rare', evolutionStage: 1 },
  { id: 252, name: 'Treecko', types: [ 'grass' ], height: 0.5, weight: 5, habitat: 'forest', evolutionStage: 1 },
  { id: 253, name: 'Grovyle', types: [ 'grass' ], height: 0.9, weight: 21.6, habitat: 'forest', evolutionStage: 2 },
  { id: 254, name: 'Sceptile', types: [ 'grass' ], height: 1.7, weight: 52.2, habitat: 'forest', evolutionStage: 3 },
  { id: 255, name: 'Torchic', types: [ 'fire' ], height: 0.4, weight: 2.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 256, name: 'Combusken', types: [ 'fire', 'fighting' ], height: 0.9, weight: 19.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 257, name: 'Blaziken', types: [ 'fire', 'fighting' ], height: 1.9, weight: 52, habitat: 'grassland', evolutionStage: 3 },
  { id: 258, name: 'Mudkip', types: [ 'water' ], height: 0.4, weight: 7.6, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 259, name: 'Marshtomp', types: [ 'water', 'ground' ], height: 0.7, weight: 28, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 260, name: 'Swampert', types: [ 'water', 'ground' ], height: 1.5, weight: 81.9, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 261, name: 'Poochyena', types: [ 'dark' ], height: 0.5, weight: 13.6, habitat: 'grassland', evolutionStage: 1 },
  { id: 262, name: 'Mightyena', types: [ 'dark' ], height: 1, weight: 37, habitat: 'grassland', evolutionStage: 2 },
  { id: 263, name: 'Zigzagoon', types: [ 'normal' ], height: 0.4, weight: 17.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 264, name: 'Linoone', types: [ 'normal' ], height: 0.5, weight: 32.5, habitat: 'grassland', evolutionStage: 2 },
  { id: 265, name: 'Wurmple', types: [ 'bug' ], height: 0.3, weight: 3.6, habitat: 'forest', evolutionStage: 1 },
  { id: 266, name: 'Silcoon', types: [ 'bug' ], height: 0.6, weight: 10, habitat: 'forest', evolutionStage: 2 },
  { id: 267, name: 'Beautifly', types: [ 'bug', 'flying' ], height: 1, weight: 28.4, habitat: 'forest', evolutionStage: 3 },
  { id: 268, name: 'Cascoon', types: [ 'bug' ], height: 0.7, weight: 11.5, habitat: 'forest', evolutionStage: 2 },
  { id: 269, name: 'Dustox', types: [ 'bug', 'poison' ], height: 1.2, weight: 31.6, habitat: 'forest', evolutionStage: 3 },
  { id: 270, name: 'Lotad', types: [ 'water', 'grass' ], height: 0.5, weight: 2.6, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 271, name: 'Lombre', types: [ 'water', 'grass' ], height: 1.2, weight: 32.5, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 272, name: 'Ludicolo', types: [ 'water', 'grass' ], height: 1.5, weight: 55, habitat: 'waters-edge', evolutionStage: 3 },
  { id: 273, name: 'Seedot', types: [ 'grass' ], height: 0.5, weight: 4, habitat: 'forest', evolutionStage: 1 },
  { id: 274, name: 'Nuzleaf', types: [ 'grass', 'dark' ], height: 1, weight: 28, habitat: 'forest', evolutionStage: 2 },
  { id: 275, name: 'Shiftry', types: [ 'grass', 'dark' ], height: 1.3, weight: 59.6, habitat: 'forest', evolutionStage: 3 },
  { id: 276, name: 'Taillow', types: [ 'normal', 'flying' ], height: 0.3, weight: 2.3, habitat: 'grassland', evolutionStage: 1 },
  { id: 277, name: 'Swellow', types: [ 'normal', 'flying' ], height: 0.7, weight: 19.8, habitat: 'grassland', evolutionStage: 2 },
  { id: 278, name: 'Wingull', types: [ 'water', 'flying' ], height: 0.6, weight: 9.5, habitat: 'sea', evolutionStage: 1 },
  { id: 279, name: 'Pelipper', types: [ 'water', 'flying' ], height: 1.2, weight: 28, habitat: 'sea', evolutionStage: 2 },
  { id: 280, name: 'Ralts', types: [ 'psychic', 'fairy' ], height: 0.4, weight: 6.6, habitat: 'urban', evolutionStage: 1 },
  { id: 281, name: 'Kirlia', types: [ 'psychic', 'fairy' ], height: 0.8, weight: 20.2, habitat: 'urban', evolutionStage: 2 },
  { id: 282, name: 'Gardevoir', types: [ 'psychic', 'fairy' ], height: 1.6, weight: 48.4, habitat: 'urban', evolutionStage: 3 },
  { id: 283, name: 'Surskit', types: [ 'bug', 'water' ], height: 0.5, weight: 1.7, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 284, name: 'Masquerain', types: [ 'bug', 'flying' ], height: 0.8, weight: 3.6, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 285, name: 'Shroomish', types: [ 'grass' ], height: 0.4, weight: 4.5, habitat: 'forest', evolutionStage: 1 },
  { id: 286, name: 'Breloom', types: [ 'grass', 'fighting' ], height: 1.2, weight: 39.2, habitat: 'forest', evolutionStage: 2 },
  { id: 287, name: 'Slakoth', types: [ 'normal' ], height: 0.8, weight: 24, habitat: 'forest', evolutionStage: 1 },
  { id: 288, name: 'Vigoroth', types: [ 'normal' ], height: 1.4, weight: 46.5, habitat: 'forest', evolutionStage: 2 },
  { id: 289, name: 'Slaking', types: [ 'normal' ], height: 2, weight: 130.5, habitat: 'forest', evolutionStage: 3 },
  { id: 290, name: 'Nincada', types: [ 'bug', 'ground' ], height: 0.5, weight: 5.5, habitat: 'forest', evolutionStage: 1 },
  { id: 291, name: 'Ninjask', types: [ 'bug', 'flying' ], height: 0.8, weight: 12, habitat: 'forest', evolutionStage: 2 },
  { id: 292, name: 'Shedinja', types: [ 'bug', 'ghost' ], height: 0.8, weight: 1.2, habitat: 'forest', evolutionStage: 2 },
  { id: 293, name: 'Whismur', types: [ 'normal' ], height: 0.6, weight: 16.3, habitat: 'cave', evolutionStage: 1 },
  { id: 294, name: 'Loudred', types: [ 'normal' ], height: 1, weight: 40.5, habitat: 'cave', evolutionStage: 2 },
  { id: 295, name: 'Exploud', types: [ 'normal' ], height: 1.5, weight: 84, habitat: 'cave', evolutionStage: 3 },
  { id: 296, name: 'Makuhita', types: [ 'fighting' ], height: 1, weight: 86.4, habitat: 'mountain', evolutionStage: 1 },
  { id: 297, name: 'Hariyama', types: [ 'fighting' ], height: 2.3, weight: 253.8, habitat: 'mountain', evolutionStage: 2 },
  { id: 298, name: 'Azurill', types: [ 'normal', 'fairy' ], height: 0.2, weight: 2, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 299, name: 'Nosepass', types: [ 'rock' ], height: 1, weight: 97, habitat: 'cave', evolutionStage: 1 },
  { id: 300, name: 'Skitty', types: [ 'normal' ], height: 0.6, weight: 11, habitat: 'grassland', evolutionStage: 1 },
  { id: 301, name: 'Delcatty', types: [ 'normal' ], height: 1.1, weight: 32.6, habitat: 'grassland', evolutionStage: 2 },
  { id: 302, name: 'Sableye', types: [ 'dark', 'ghost' ], height: 0.5, weight: 11, habitat: 'cave', evolutionStage: 1 },
  { id: 303, name: 'Mawile', types: [ 'steel', 'fairy' ], height: 0.6, weight: 11.5, habitat: 'cave', evolutionStage: 1 },
  { id: 304, name: 'Aron', types: [ 'steel', 'rock' ], height: 0.4, weight: 60, habitat: 'mountain', evolutionStage: 1 },
  { id: 305, name: 'Lairon', types: [ 'steel', 'rock' ], height: 0.9, weight: 120, habitat: 'mountain', evolutionStage: 2 },
  { id: 306, name: 'Aggron', types: [ 'steel', 'rock' ], height: 2.1, weight: 360, habitat: 'mountain', evolutionStage: 3 },
  { id: 307, name: 'Meditite', types: [ 'fighting', 'psychic' ], height: 0.6, weight: 11.2, habitat: 'mountain', evolutionStage: 1 },
  { id: 308, name: 'Medicham', types: [ 'fighting', 'psychic' ], height: 1.3, weight: 31.5, habitat: 'mountain', evolutionStage: 2 },
  { id: 309, name: 'Electrike', types: [ 'electric' ], height: 0.6, weight: 15.2, habitat: 'grassland', evolutionStage: 1 },
  { id: 310, name: 'Manectric', types: [ 'electric' ], height: 1.5, weight: 40.2, habitat: 'grassland', evolutionStage: 2 },
  { id: 311, name: 'Plusle', types: [ 'electric' ], height: 0.4, weight: 4.2, habitat: 'grassland', evolutionStage: 1 },
  { id: 312, name: 'Minun', types: [ 'electric' ], height: 0.4, weight: 4.2, habitat: 'grassland', evolutionStage: 1 },
  { id: 313, name: 'Volbeat', types: [ 'bug' ], height: 0.7, weight: 17.7, habitat: 'grassland', evolutionStage: 1 },
  { id: 314, name: 'Illumise', types: [ 'bug' ], height: 0.6, weight: 17.7, habitat: 'grassland', evolutionStage: 1 },
  { id: 315, name: 'Roselia', types: [ 'grass', 'poison' ], height: 0.3, weight: 2, habitat: 'grassland', evolutionStage: 2 },
  { id: 316, name: 'Gulpin', types: [ 'poison' ], height: 0.4, weight: 10.3, habitat: 'grassland', evolutionStage: 1 },
  { id: 317, name: 'Swarot', types: [ 'poison' ], height: 1.7, weight: 80, habitat: 'grassland', evolutionStage: 2 },
  { id: 318, name: 'Carvanha', types: [ 'water', 'dark' ], height: 0.8, weight: 20.8, habitat: 'sea', evolutionStage: 1 },
  { id: 319, name: 'Sharpedo', types: [ 'water', 'dark' ], height: 1.8, weight: 88.8, habitat: 'sea', evolutionStage: 2 },
  { id: 320, name: 'Wailmer', types: [ 'water' ], height: 2, weight: 130, habitat: 'sea', evolutionStage: 1 },
  { id: 321, name: 'Wailord', types: [ 'water' ], height: 14.5, weight: 398, habitat: 'sea', evolutionStage: 2 },
  { id: 322, name: 'Numel', types: [ 'fire', 'ground' ], height: 0.7, weight: 24, habitat: 'mountain', evolutionStage: 1 },
  { id: 323, name: 'Camerupt', types: [ 'fire', 'ground' ], height: 1.9, weight: 220, habitat: 'mountain', evolutionStage: 2 },
  { id: 324, name: 'Torkoal', types: [ 'fire' ], height: 0.5, weight: 80.4, habitat: 'mountain', evolutionStage: 1 },
  { id: 325, name: 'Spoink', types: [ 'psychic' ], height: 0.7, weight: 30.6, habitat: 'mountain', evolutionStage: 1 },
  { id: 326, name: 'Grumpig', types: [ 'psychic' ], height: 0.9, weight: 71.5, habitat: 'mountain', evolutionStage: 2 },
  { id: 327, name: 'Spinda', types: [ 'normal' ], height: 1.1, weight: 5, habitat: 'mountain', evolutionStage: 1 },
  { id: 328, name: 'Trapinch', types: [ 'ground' ], height: 0.7, weight: 15, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 329, name: 'Vibrava', types: [ 'ground', 'dragon' ], height: 1.1, weight: 15.3, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 330, name: 'Flygon', types: [ 'ground', 'dragon' ], height: 2, weight: 82, habitat: 'rough-terrain', evolutionStage: 3 },
  { id: 331, name: 'Cacnea', types: [ 'grass' ], height: 0.4, weight: 51.3, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 332, name: 'Cacturne', types: [ 'grass', 'dark' ], height: 1.3, weight: 77.4, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 333, name: 'Swablu', types: [ 'normal', 'flying' ], height: 0.4, weight: 1.2, habitat: 'forest', evolutionStage: 1 },
  { id: 334, name: 'Altaria', types: [ 'dragon', 'flying' ], height: 1.1, weight: 20.6, habitat: 'forest', evolutionStage: 2 },
  { id: 335, name: 'Zangoose', types: [ 'normal' ], height: 1.3, weight: 40.3, habitat: 'grassland', evolutionStage: 1 },
  { id: 336, name: 'Seviper', types: [ 'poison' ], height: 2.7, weight: 52.5, habitat: 'grassland', evolutionStage: 1 },
  { id: 337, name: 'Lunatone', types: [ 'rock', 'psychic' ], height: 1, weight: 168, habitat: 'cave', evolutionStage: 1 },
  { id: 338, name: 'Solrock', types: [ 'rock', 'psychic' ], height: 1.2, weight: 154, habitat: 'cave', evolutionStage: 1 },
  { id: 339, name: 'Barboach', types: [ 'water', 'ground' ], height: 0.4, weight: 1.9, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 340, name: 'Whiscash', types: [ 'water', 'ground' ], height: 0.9, weight: 23.6, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 341, name: 'Corphish', types: [ 'water' ], height: 0.6, weight: 11.5, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 342, name: 'Crawdaunt', types: [ 'water', 'dark' ], height: 1.1, weight: 32.8, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 343, name: 'Baltoy', types: [ 'ground', 'psychic' ], height: 0.5, weight: 21.5, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 344, name: 'Claydol', types: [ 'ground', 'psychic' ], height: 1.5, weight: 108, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 345, name: 'Lileep', types: [ 'rock', 'grass' ], height: 1, weight: 23.8, habitat: 'sea', evolutionStage: 1 },
  { id: 346, name: 'Cradily', types: [ 'rock', 'grass' ], height: 1.5, weight: 60.4, habitat: 'sea', evolutionStage: 2 },
  { id: 347, name: 'Anorith', types: [ 'rock', 'bug' ], height: 0.7, weight: 12.5, habitat: 'sea', evolutionStage: 1 },
  { id: 348, name: 'Armaldo', types: [ 'rock', 'bug' ], height: 1.5, weight: 68.2, habitat: 'sea', evolutionStage: 2 },
  { id: 349, name: 'Feebas', types: [ 'water' ], height: 0.6, weight: 7.4, habitat: 'waters-edge', evolutionStage: 1 },
  { id: 350, name: 'Milotic', types: [ 'water' ], height: 6.2, weight: 162, habitat: 'waters-edge', evolutionStage: 2 },
  { id: 351, name: 'Castform', types: [ 'normal' ], height: 0.3, weight: 0.8, habitat: 'grassland', evolutionStage: 1 },
  { id: 352, name: 'Kecleon', types: [ 'normal' ], height: 1, weight: 22, habitat: 'forest', evolutionStage: 1 },
  { id: 353, name: 'Shuppet', types: [ 'ghost' ], height: 0.6, weight: 2.3, habitat: 'urban', evolutionStage: 1 },
  { id: 354, name: 'Banette', types: [ 'ghost' ], height: 1.1, weight: 12.5, habitat: 'urban', evolutionStage: 2 },
  { id: 355, name: 'Duskull', types: [ 'ghost' ], height: 0.8, weight: 15, habitat: 'forest', evolutionStage: 1 },
  { id: 356, name: 'Dusclops', types: [ 'ghost' ], height: 1.6, weight: 30.6, habitat: 'forest', evolutionStage: 2 },
  { id: 357, name: 'Tropius', types: [ 'grass', 'flying' ], height: 2, weight: 100, habitat: 'forest', evolutionStage: 1 },
  { id: 358, name: 'Chimecho', types: [ 'psychic' ], height: 0.6, weight: 1, habitat: 'mountain', evolutionStage: 2 },
  { id: 359, name: 'Absol', types: [ 'dark' ], height: 1.2, weight: 47, habitat: 'mountain', evolutionStage: 1 },
  { id: 360, name: 'Wynaut', types: [ 'psychic' ], height: 0.6, weight: 14, habitat: 'cave', evolutionStage: 1 },
  { id: 361, name: 'Snorunt', types: [ 'ice' ], height: 0.7, weight: 16.8, habitat: 'cave', evolutionStage: 1 },
  { id: 362, name: 'Glalie', types: [ 'ice' ], height: 1.5, weight: 256.5, habitat: 'cave', evolutionStage: 2 },
  { id: 363, name: 'Spheal', types: [ 'ice', 'water' ], height: 0.8, weight: 39.5, habitat: 'sea', evolutionStage: 1 },
  { id: 364, name: 'Sealeo', types: [ 'ice', 'water' ], height: 1.1, weight: 87.6, habitat: 'sea', evolutionStage: 2 },
  { id: 365, name: 'Walrein', types: [ 'ice', 'water' ], height: 1.4, weight: 150.6, habitat: 'sea', evolutionStage: 3 },
  { id: 366, name: 'Clamperl', types: [ 'water' ], height: 0.4, weight: 52.5, habitat: 'sea', evolutionStage: 1 },
  { id: 367, name: 'Huntail', types: [ 'water' ], height: 1.7, weight: 27, habitat: 'sea', evolutionStage: 2 },
  { id: 368, name: 'Gorebyss', types: [ 'water' ], height: 1.8, weight: 22.6, habitat: 'sea', evolutionStage: 2 },
  { id: 369, name: 'Relicanth', types: [ 'water', 'rock' ], height: 1, weight: 23.4, habitat: 'sea', evolutionStage: 1 },
  { id: 370, name: 'Luvdisc', types: [ 'water' ], height: 0.6, weight: 8.7, habitat: 'sea', evolutionStage: 1 },
  { id: 371, name: 'Bagon', types: [ 'dragon' ], height: 0.6, weight: 42.1, habitat: 'mountain', evolutionStage: 1 },
  { id: 372, name: 'Shelgon', types: [ 'dragon' ], height: 1.1, weight: 110.5, habitat: 'mountain', evolutionStage: 2 },
  { id: 373, name: 'Salamence', types: [ 'dragon', 'flying' ], height: 1.5, weight: 102.6, habitat: 'mountain', evolutionStage: 3 },
  { id: 374, name: 'Beldum', types: [ 'steel', 'psychic' ], height: 0.6, weight: 95.2, habitat: 'rough-terrain', evolutionStage: 1 },
  { id: 375, name: 'Metang', types: [ 'steel', 'psychic' ], height: 1.2, weight: 202.5, habitat: 'rough-terrain', evolutionStage: 2 },
  { id: 376, name: 'Metagross', types: [ 'steel', 'psychic' ], height: 1.6, weight: 550, habitat: 'rough-terrain', evolutionStage: 3 },
  { id: 377, name: 'Regirock', types: [ 'rock' ], height: 1.7, weight: 230, habitat: 'rare', evolutionStage: 1 },
  { id: 378, name: 'Regice', types: [ 'ice' ], height: 1.8, weight: 175, habitat: 'rare', evolutionStage: 1 },
  { id: 379, name: 'Registeel', types: [ 'steel' ], height: 1.9, weight: 205, habitat: 'rare', evolutionStage: 1 },
  { id: 380, name: 'Latias', types: [ 'dragon', 'psychic' ], height: 1.4, weight: 40, habitat: 'rare', evolutionStage: 1 },
  { id: 381, name: 'Latios', types: [ 'dragon', 'psychic' ], height: 2, weight: 60, habitat: 'rare', evolutionStage: 1 },
  { id: 382, name: 'Kyogre', types: [ 'water' ], height: 4.5, weight: 352, habitat: 'rare', evolutionStage: 1 },
  { id: 383, name: 'Groudon', types: [ 'ground' ], height: 3.5, weight: 950, habitat: 'rare', evolutionStage: 1 },
  { id: 384, name: 'Rayquaza', types: [ 'dragon', 'flying' ], height: 7, weight: 206.5, habitat: 'rare', evolutionStage: 1 },
  { id: 385, name: 'Jirachi', types: [ 'steel', 'psychic' ], height: 0.3, weight: 1.1, habitat: 'rare', evolutionStage: 1 },
  { id: 386, name: 'Deoxys', types: [ 'psychic' ], height: 1.7, weight: 60.8, habitat: 'rare', evolutionStage: 1 }
];
